### ISSUE TITLE
Yalc don't work with package that have @ in their name

### ISSUE THREAD

**Issue by rorp24** [wclr/yalc#184]
I want to use a local package that will have an @ in it. I can publish the package in yalc, but when I want to add it, it give me this error:
```
$ yalc add @package-name
Could not find package `package-name` in store (C:\Users\me\AppData\Local\Yalc\packages\package-name), skipping.
```
Turn out when I add it in yalc, it is registered as `C:\Users\me\AppData\Local\Yalc\packages\@package-name` but the add command remove the @.

How can I solve this issue.

I use yalc 1.0.0-pre.53

**Comment by Domiii** [comment]
@rorp24 I am not sure why you would prefix a package name with `@`.
Usually, `@` is used for [scopes](https://docs.npmjs.com/cli/v8/using-npm/scope), not for names. Meaning, the full name should have a slash (`/`) on top of the preceeding `@`.

e.g. if you name it `@a/b`, it should work.

I use scoped package names and it works for me.
However, I have never tried naming a package just `@a`.

**Comment by wclr** [comment]
Closing this.

**Comment by cryptofelon** [comment]
It seems like yalc's `postyalc` scripts don't work with packages having `@` in their name (such as packages belonging to organizations, ex `@exampleGithubOrg/package-name`).
Every time I run a postyalc script:
```
"postyalc.@exampleorg/example": "node ./build_scripts/copyMapAssets.js",
"postyalc.@exampleorg/example2": "yarn s:run-copy-map-asets",
(or)

```
It triggers a `yarn install` rather than actually runs the command. Which seems to be similar behavior to when I try to run any `yarn` command starting with `@` (of which there are none).

Though the Postyalc does get triggered, the execution after the fact seems bugged.
```
Running postyalc.@exampleorg/example2: yarn s:run-copy-map-asets
```

Any idea on how to fix this? @wclr

**Comment by wclr** [comment]
> 
> 
> Any idea on how to fix this? @wclr
> 
> Edit: The problem is with "/" not "@"

Does it give an error?

**Comment by cryptofelon** [comment]
> > Any idea on how to fix this? @wclr
> > Edit: The problem is with "/" not "@"
> 
> Does it give an error?

No it doesn't give an error, but I've figured out the problem.

I'm using Yarn 4.0. Yarn underwent some big changes after Yarn 2.0. I assume this package was originally written during the time of Yarn 1.0.

On Yarn 4.0, running a command with a slash in it as a script name, eg `yarn postyalc.@exampleOrg/example-pkg` , or `yarn example/` results in a `yarn install` rather than actually running a script by script name.
However, `yarn run postyalc.@exampleOrg/example-pkg` works perfectly fine.


I saw in [pm.ts](https://github.com/wclr/yalc/blob/master/src/pm.ts) that in `pmRunScriptCmd`, `npm` already was using the `run` keyword. I'm not sure if Yarn 1.0 supported the `yarn run` command, but if it did, then changing this:
```
export const pmRunScriptCmd: { [P in PackageMangerName]: string } = {
  pnpm: 'pnpm',
  yarn: 'yarn',
  npm: 'npm run',
}
```
may be a good fix.

Otherwise, perhaps [line 78 here](https://github.com/wclr/yalc/blob/3b834e488837e87df47414fd9917c10f07f0df08/src/add.ts#L78) should be changed to:
```
      execSync(`${scriptCmd}`, {
        cwd: workingDir,
        ...execLoudOptions,
      })

```
so that it's agnostic of the package manager being used, and instead have users define if they want to call `yarn` or `npm` from within their package.json?

allowing for ex:
```
		"s:1": "echo POST PUSH",
		"postyalc.@exOrg/ex-pkg": "yarn s:1 && yarn s:copy-map-assets && node ./build_scripts/example.js",

```
